events:
  daily:
    times:
      - "10:00"  # 10:00 AM BST
      - "14:00"  # 2:00 PM BST
      - "18:00"  # 6:00 PM BST
      - "22:00"  # 10:00 PM BST
      - "02:00"  # 2:00 AM BST
      - "06:00"  # 6:00 AM BST
    possible_events:
      - command: "crates giveall common 1"
        name: "Daily Keyall"
      - command: "envoy start"
        name: "Daily Envoy"
      - command: "koth start SkyCloud_1"
        name: "Daily KoTH (SkyCloud 1)"
      - command: "koth start SkyCloud_2"
        name: "Daily KoTH (SkyCloud 2)"
    broadcast: "&6&l{event} &e&lstarting now!"
    countdown:
      enabled: true
      duration: 10  # Countdown duration in seconds
      messages:
        - "&aEvent starting in &e10 &aseconds!"
        - "&aEvent starting in &e5 &aseconds!"
        - "&aEvent starting in &e4 &aseconds!"
        - "&aEvent starting in &e3 &aseconds!"
        - "&aEvent starting in &e2 &aseconds!"
        - "&aEvent starting in &e1 &asecond!"
      sound: "BLOCK_NOTE_BLOCK_PLING"  # Sound effect to play during countdown

hologram:
  enabled: true
  location:
    world: world
    x: 100
    y: 64
    z: 200
  text: "&aNext Event: &e{event} at &6{time}"
